# Zensical Configuration
# Documentation: https://zensical.org/docs/setup/basics/

[project]
site_name = "landerox.com"
site_url = "https://landerox.com"
site_description = "Personal portfolio and engineering blog showcasing cloud architecture patterns and open source projects."
site_author = "Fernando Landero"
copyright = "Â© 2025 Fernando Landero"

docs_dir = "docs"
site_dir = "site"

extra_css = ["assets/stylesheets/extra.css"]

# Navigation structure
nav = [
  { "Home" = "index.md" },
  { "Projects" = "projects/index.md"},
  { "Radar" = "radar/index.md"},
  { "Resume" = "resume/index.md"},
]

# Theme configuration
[project.theme]
variant = "modern"
favicon = "assets/images/favicon.ico"
logo = "assets/images/logo.svg"

features = [
  "navigation.instant",
  "navigation.instant.prefetch",
  "navigation.instant.progress",
  "navigation.tracking",
  "navigation.tabs",
  "navigation.sections",
  "navigation.indexes",
  "navigation.top",
  "navigation.path",
  "toc.follow",
  "search.suggest",
  "search.highlight",
  "navigation.footer",
]

[project.theme.palette]
scheme = "slate"
primary = "indigo"
accent = "indigo"

# Social links (footer)
[[project.extra.social]]
icon = "material/web"
link = "https://linktr.ee/landerox"

# Markdown extensions
[project.markdown_extensions.toc]
permalink = false

# Highlight & Code Blocks
[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true

[project.markdown_extensions.pymdownx.superfences]
[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.snippets]

# Tabs
[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true

# Emojis
[project.markdown_extensions.pymdownx.emoji]
emoji_index = "zensical.extensions.emoji.twemoji"
emoji_generator = "zensical.extensions.emoji.to_svg"

# Other Utilities
[project.markdown_extensions.admonition]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.blocks]
[project.markdown_extensions.attr_list]
[project.markdown_extensions.md_in_html]
